language: node_js
node_js:
- 10.16.3
services: mongodb
cache:
- node_modules
deploy:
  provider: heroku
  api_key:
    secure: zU2XbbbPrCkAhBwEHvGrxVHvpqvHHD9gWDjm0NaXj01WFnHKYoFI+jx0oTaaR8YWqRlRXtWy7TBjmwmXGSl1uV9nQ9NE/zPboehNj71Xa9lxAi9/1Jpi419byW6KwCf6Qcnl7hX4CpYB3Y5MFI5nDC14QwhwTGlF8tObN15Y7RhX6X7JYudCbjkB+cMHKIparyKXmfkOoeZ14RrzIuExm6xF5q+QSDQ+delsdGbDE9ybzaRo92CTfAZUg9QvC6Q9JtrmrsXEx23D+8tI6jfLe1ql4Ng+M9PzhJYgiJf9yL4O6ttDvA+QmUJyDi3ethd+Offac0BfTdfzw0VQ3xtAS/c7TWzor3yKYtaIml77+Q3wJt1/3MqPYYj6TN/Yi8Ie7lcTIj6KyXqYV1gzrGFv8PZN5g52aSTAG+wEPvqlgZtzHkrnyWFPX2UwRJCVQjuCf8CyXncMwOJBvu6+FW1S1gj4CsIPKFHnhdeBSnJxLng4kNAJPqD2AW9dgScc1GJvGUYCTHR4sJovUt7UhwG3UmL16KFUNRSSZS8AVceCIvXRYBkYv+UPi6605ukXFUVPyyow6T2thLILmYNZzMBtLdbwlBVVp02zXiZezvshG00uBQ+xPMRWti0DBDI8QLX6VvJAL+a1akXbuAmVPTWffvSyI8geB6rFT8Xmqm7HODQ=
  app: messagebox
  on:
    repo: minernchan/OTOTassignmentB
