language: node_js
node_js:
  - 10.16.3
services: mongodb

deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules

install:
    - npm install -g serverless
    - travis_retry npm install


script:
    - serverless deploy -s ${STAGE_NAME}


environments:
  - &DEVELOPMENT_ENV
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_DEVELOPMENT}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_DEVELOPMENT}

jobs:
  include:
    # develop branch deploys to the 'dev' stage
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy MessageBox API"
      if: type = push AND branch = develop
      env:
        # - SERVICE_PATH=""
        - STAGE_NAME=dev
        - *DEVELOPMENT_ENV